//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long Key { get; set; }
        public long TodoKey { get; set; }
        public string UserName { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime CommentDate { get; set; }
        public bool Deleted { get; set; }
    }
}
