//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public long Key { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Done { get; set; }
    }
}
